<?php
/**
 * @file
 * Code for the Farm Maple feature.
 */

include_once 'farm_maple.features.inc';

/**
 * Implements hook_farm_ui_entities().
 */
function farm_maple_farm_ui_entities() {
  return array(
    'farm_asset' => array(
      'sugar_bush' => array(
        'label' => t('Sugar Bush'),
        'label_plural' => t('Sugar Bushes'),
        'view' => 'farm_sugar_bushes',
      ),
    ),
    'log' => array(
      'farm_tap' => array(
        'label' => t('Tap log'),
        'label_plural' => t('Tap logs'),
        'view' => 'farm_log_tap',
        'farm_asset' => 'sugar_bush',
        'weight' => -99,
      ),
    ),
  );
}

/**
 * Implements hook_farm_log_categories().
 */
function farm_maple_farm_log_categories() {

  // Provide an "Maple" log category.
  return array('Maple');
}
